esphome:
  name: brmesh
  friendly_name: BRMesh

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: github://zentik-fr/esphome-brmesh@main
    components: [fastcon]

esp32_ble_tracker:
esp32_ble_server:

logger:

api:
  encryption:
    key: "479yaWrhH/nMr2vYAMmCqWxH70rSi3Zry5/BZMcMwxU="

ota:
  - platform: esphome
    password: "bf627630bcdd68b1f93b14e5855b495"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "BRMESH Fallback Hotspot"
    password: "CKD41Oj&ccAEJI"

captive_portal:

fastcon:
  mesh_key: "56219394"

  # Paramètres selon le protocole BRMesh observé:
  adv_interval_min: 0x20  # Minimum advertisement interval (BLE low-level parameter)
  adv_interval_max: 0x40  # Maximum advertisement interval (BLE low-level parameter)
  adv_duration: 15        # Durée de diffusion BLE en ms (courte pour permettre envoi rapide)
  max_queue_size: 100     # Maximum number of queued commands
  command_retries: 20     # Nombre d'envois par commande (spec BRMesh: 15-30, recommandé: 20)
  command_interval: 25    # Délai TOTAL entre deux envois en ms (spec BRMesh: 20-30ms, recommandé: 25ms)
  # Résultat: 20 paquets × 25ms = 500ms par commande (conforme spec BRMesh: 300-800ms)

light:
  - platform: fastcon
    id: brmesh_lamp_1
    name: "Lamp1"
    light_id: 1
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
    # Effects will be enabled once protocol is discovered via BLE sniffing
    # Uncomment and customize once effect codes are known:
    # effects:
    #   - strobe:
    #       name: "Strobe"
    #   - pulse:
    #       name: "Pulse"
    #   - random:
    #       name: "Random"

  - platform: fastcon
    id: brmesh_lamp_2
    name: "Lamp2"
    light_id: 2
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
    # effects:
    #   - strobe:
    #   - pulse:

  - platform: fastcon
    id: brmesh_lamp_3
    name: "Lamp3"
    light_id: 3
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: fastcon
    id: brmesh_lamp_4
    name: "Lamp4"
    light_id: 4
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
