esphome:
  name: brmesh
  friendly_name: BRMesh

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: 
      type: git
      url: https://github.com/zentik-fr/esphome-brmesh
      ref: main
    refresh: 0s
    components: [fastcon]

esp32_ble_tracker:
esp32_ble_server:

logger:

api:
  encryption:
    key: "479yaWrhH/nMr2vYAMmCqWxH70rSi3Zry5/BZMcMwxU="

ota:
  - platform: esphome
    password: "bf627630bcdd68b1f93b14e5855b495"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "BRMESH Fallback Hotspot"
    password: "CKD41Oj&ccAEJI"

captive_portal:

fastcon:
  mesh_key: "56219394"

  # Paramètres selon le protocole BRMesh observé:
  adv_interval_min: 0x20  # Minimum advertisement interval (BLE low-level parameter)
  adv_interval_max: 0x40  # Maximum advertisement interval (BLE low-level parameter)
  adv_duration: 15        # Durée de diffusion BLE en ms (courte pour permettre envoi rapide)
  max_queue_size: 100     # Maximum number of queued commands
  command_retries: 20     # Nombre d'envois par commande (spec BRMesh: 15-30, recommandé: 20)
  command_interval: 25    # Délai TOTAL entre deux envois en ms (spec BRMesh: 20-30ms, recommandé: 25ms)
  # Résultat: 20 paquets × 25ms = 500ms par commande (conforme spec BRMesh: 300-800ms)

light:
  - platform: fastcon
    id: brmesh_lamp_1
    name: "Lamp1"
    light_id: 1
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      # Effets avec variantes de vitesse : Slow (25), Medium (50 - défaut), Fast (75)
      
      # Type 0x48: Simple effects
      - lambda:
          name: "Christmas Slow"
          update_interval: 16ms
          lambda: |-
            // Speed 25
      - lambda:
          name: "Christmas"
          update_interval: 16ms
          lambda: |-
            // Speed 50 (default)
      - lambda:
          name: "Christmas Fast"
          update_interval: 16ms
          lambda: |-
            // Speed 75
            
      - lambda:
          name: "Romantic Slow"
          update_interval: 16ms
          lambda: |-
            // Speed 25
      - lambda:
          name: "Romantic"
          update_interval: 16ms
          lambda: |-
            // Speed 50
      - lambda:
          name: "Romantic Fast"
          update_interval: 16ms
          lambda: |-
            // Speed 75
            
      - lambda:
          name: "Cozy"
          update_interval: 16ms
          lambda: |-
            // Speed 50
      - lambda:
          name: "Winter"
          update_interval: 16ms
          lambda: |-
            // Speed 50
      - lambda:
          name: "Halloween"
          update_interval: 16ms
          lambda: |-
            // Speed 50
      - lambda:
          name: "Valentines"
          update_interval: 16ms
          lambda: |-
            // Speed 50
            
      # Type 0x58: Medium effects
      - lambda:
          name: "Fresh"
          update_interval: 16ms
          lambda: |-
            // Speed 50
      - lambda:
          name: "Three Color Flash Slow"
          update_interval: 16ms
          lambda: |-
            // Speed 25 (inverted to 75 for flash)
      - lambda:
          name: "Three Color Flash"
          update_interval: 16ms
          lambda: |-
            // Speed 50
      - lambda:
          name: "Three Color Flash Fast"
          update_interval: 16ms
          lambda: |-
            // Speed 75 (inverted to 25 for flash)
            
      # Type 0x88: Complex effects
      - lambda:
          name: "Full Color Fade Slow"
          update_interval: 16ms
          lambda: |-
            // Speed 25
      - lambda:
          name: "Full Color Fade"
          update_interval: 16ms
          lambda: |-
            // Speed 50
      - lambda:
          name: "Full Color Fade Fast"
          update_interval: 16ms
          lambda: |-
            // Speed 75
            
      - lambda:
          name: "Full Color Flash Slow"
          update_interval: 16ms
          lambda: |-
            // Speed 25 (inverted to 75 for flash)
      - lambda:
          name: "Full Color Flash"
          update_interval: 16ms
          lambda: |-
            // Speed 50
      - lambda:
          name: "Full Color Flash Fast"
          update_interval: 16ms
          lambda: |-
            // Speed 75 (inverted to 25 for flash)

  - platform: fastcon
    id: brmesh_lamp_2
    name: "Lamp2"
    light_id: 2
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      # Type 0x48: Simple effects (1 parameter)
      - lambda:
          name: "Romantic"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Cozy"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Christmas"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Winter"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Halloween"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Valentines"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      # Type 0x58: Medium effects (2 parameters)
      - lambda:
          name: "Fresh"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Three Color Flash"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      # Type 0x88: Complex effects (5 parameters)
      - lambda:
          name: "Full Color Fade"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Full Color Flash"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol


  - platform: fastcon
    id: brmesh_lamp_3
    name: "Lamp3"
    light_id: 3
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      # Type 0x48: Simple effects (1 parameter)
      - lambda:
          name: "Romantic"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Cozy"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Christmas"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Winter"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Halloween"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Valentines"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      # Type 0x58: Medium effects (2 parameters)
      - lambda:
          name: "Fresh"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Three Color Flash"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      # Type 0x88: Complex effects (5 parameters)
      - lambda:
          name: "Full Color Fade"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Full Color Flash"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol


  - platform: fastcon
    id: brmesh_lamp_4
    name: "Lamp4"
    light_id: 4
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      # Type 0x48: Simple effects (1 parameter)
      - lambda:
          name: "Romantic"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Cozy"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Christmas"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Winter"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Halloween"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Valentines"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      # Type 0x58: Medium effects (2 parameters)
      - lambda:
          name: "Fresh"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Three Color Flash"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      # Type 0x88: Complex effects (5 parameters)
      - lambda:
          name: "Full Color Fade"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol
      - lambda:
          name: "Full Color Flash"
          update_interval: 16ms
          lambda: |-
            // Effect handled by BRMesh protocol

